[dracula]
  gray1 = "#464752"
  gray2 = "#565761"
  gray3 = "#b6b6b2"
  gray4 = "#ccccc7"
  black = "#282a36"
  blue = "#6272a4"
  cyan = "#8be9fd"
  green = "#50fa7b"
  magenta = "#ff79c6"
  orange = "#ffb86c"
  purple = "#bd93f9"
  red = "#ff5555"
  white = "#f8f8f2"
  yellow = "#f1fa8c"
