
[main]
  color-tsharks = ["/usr/bin/tshark"]
  dark-mode = true
  last-used-tshark = "/usr/bin/tshark"
  packet-colors = false
  theme-truecolor = "dracula"
  validated-tsharks = ["/usr/bin/tshark"]
