require("keymap")

require("color")
require("git")
require("register")
require("colorizer").setup()
require("statusline")
require("bufferln")
require("file-tree")
require("tele")
require("lsp")
require("treesitter")
require("indent")
require("autopairs")
require("debugger")
require("term")
require("rest")
require("session")
require("save")
require("refactor")
require("octo").setup()
require("rename")
require("go").setup()
-- require('discord-presence')
