
require("color")
require("keymap")
require("autopairs")
-- require("bufferln")

require("comment")
require("debugger")
-- require('discord-presence')
require("file-tree")
require("git")
require("harpoonconfig")
require("indent")

require("lsp")
require("refactor")
require("rename")
require("rest")
require("save")
require("session")
require("statusline")
require("tele")
require("term")

require("colorizer").setup()
require("treesitter")
require("octo").setup()
require("go").setup()
